### ISSUE TITLE
Doesn't work anymore with current js-controller 5.0.2

### ISSUE THREAD

**Issue by pfanntec** [iobroker-community-adapters/ioBroker.pushbullet#44]
Does not start with current js-controller 5.0.2.
After a downgrade to 4.0.24 it works again.

**Versions:**  
 - Adapter version: 0.0.11
 - JS-Controller version: 5.0.2
 - Node version: v18.16.0
 - Operating system: Debian 12 (Bookworm)

**Comment by mcm1957** [comment]
@pfanntec 
Please check with current GITHUB version.

And if it does not work as expeczted, please provide a log.

Thanks

**Comment by pfanntec** [comment]
Works again. Thank you very much for fixing.

pushbullet adapter 0.1.0
js-controller 5.0.12
node 18.17.1
npm 9.6.7

**Comment by mcm1957** [comment]
Thanjs for feedback 

Keeping issue open until a true release is published.

**Comment by mcm1957** [comment]
alpha release published, lates release will follow in a few days
Test Thread https://forum.iobroker.net/topic/68741/test-adapter-pushbullet-v2-0-x

will close here, please open a new issue if any problems occure
